sharedGlobals: &sharedGlobals
  - ".gitignore"
  - ".node-version"
  - "package.json"
  - "pnpm-lock.yaml"

eslintGlobals: &eslintGlobals
  - "eslint.config.mjs"

prettierGlobals: &prettierGlobals
  - ".editorconfig"
  - ".prettierignore"
  - ".prettierrc.mjs"

ci: &ci
  - ".github/workflows/ci.yml"

production: &production
  - *sharedGlobals
  - *ci
  - "src/**/!(*.test).{js,mjs,cjs,ts,cts,mts,astro,vue}"
  - "public/**/*"
  - "astro.config.mjs"
  - "tailwind.config.ts"
  - "tsconfig.json"

lint:
  - *sharedGlobals
  - *eslintGlobals
  - *ci
  - "**/*.{js,cjs,mjs,ts,cts,mts,astro,vue}"
  - "tsconfig.json"

build:
  - *production

lighthouse:
  - *production
  - lighthouserc.cjs
